config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # verb "/path", to: "controller#action"
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"

  root to: "pages#home", as: :home

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact

    @members = ["Margarida", "João", "Rita", "Ricardo", "Miguel", "David"]

    search = params[:member]

    if search
      @members = @members.select {|member| member.start_with? search.capitalize }
    end

  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Our first rails app!</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>This is a navbar</h1>
    <%= yield %>
    <p>this is a footer</p>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page! 🧑‍🌾</h1>

app/views/pages/contact.html.erb
<h1>This is our contact page 😎</h1>

<p>These are the people you can contact: </p>

<form action="/contact" method="get">
  <input type="text" name="member" value="<%= params[:member] %>">
  <input type="submit">
</form>


<ol>
  <% @members.each do |member| %>
  <li><%= member %></li>
  <% end %>
</ol>

<%= link_to "Homepage", home_path %>

app/views/pages/home.html.erb
<h1>Welcome to the best app ever 🚀</h1>
<%= link_to "Contact Us", contact_path %>